### ISSUE TITLE
App launch checklist

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-website-licensing-server#14]
## Description
Before pushing this app to production, we have to make sure we have taken care of the following items.
- [ ] Setup redirect on pages as we did for staging.givewp.com.
Live site URL: https://licensing.givewp.com/
Pagely discussion: https://atomic-beta.pagely.com/account/13588/support/156834

- [ ] Merge `lumen` branch of `Give-EDD-Software-Licensing-API-Extended ` git repo to `master` and push the latest changes to `givewp.com`

- [ ] Add this snippet to `wp.config.php` of `givewp.com`
**Note:** we can also confirm from Pagely is `$_SERVER['SERVER_NAME']` good way to detect staging site.

```
if( false !== strpos( $_SERVER['SERVER_NAME'], 'staging')){
	define( 'LUMEN_SERVER_URI', 'https://staging.licensing.givewp.com/' );
	define( 'LUMEN_USER_EMAIL', 'devin@givewp.com' );
	define( 'LUMEN_USER_PASSWORD', '9hqbs#kZ}-&aRF4{-staging' );
} else{
	define( 'LUMEN_SERVER_URI', 'https://licensing.givewp.com/' );
	define( 'LUMEN_USER_EMAIL', 'devin@givewp.com' );
	define( 'LUMEN_USER_PASSWORD', '$7_KHzyw2`$csNNU-production' );
}
```

- [ ] Confirm from Pagely that we do not have any rate limiting condition for https://licensing.givewp.com/ or https://staging.licensing.givewp.com/

After launch we can take the following actions:
- [ ] Visit https://licensing.givewp.com/app/update to run update. It will install tables to the production server.
- [ ] Test `edd-sl-api` endpoint of `givewp.com`
